Add some examples and the beginnings of the grammar.
mylk-pl/mylk-meta pull request #2
Opened 2020-12-15 15:51 UTC by Jackojc

2020-12-15 16:00 UTC, noxabellus commented on grammar.ebnf
> +escapes = '\n' | '\t' | '\r' | '\v' | '\f' | '\b' | '\'' | '\"' | '\\' | unicode_escape | hex_escape | bin_escape
Looks like the escaped single quote isnt recognized as being escaped...Maybe use `"'"` instead of `'\''`

2020-12-15 16:25 UTC, dekrain reviewed
Review for ya :slightly_smiling_face:

2020-12-15 16:25 UTC, dekrain commented on examples/ack.mlk
> +}
Fixed version
```
fn ackermann(m, n: int) int {
    if m == 0 {
        n + 1
    } else if n == 0 {
        ackermann(m - 1, 1)
    } else {
        ackermann(m - 1, ackermann(m, n - 1))
    }
}
```

2020-12-15 16:25 UTC, dekrain commented on grammar.ebnf
> +for = 'for' identifier [':' type] '=' expr ',' expr [',' expr] block
I think, supported by the examples, that it should be
```ebnf
for = 'for' identifier ':' [type] '=' expr ',' expr [',' expr] block
```

2020-12-15 16:25 UTC, dekrain commented on grammar.ebnf
> +hex_escape = '\x' hex+
I think it better works as
```ebnf
unicode_escape = '\u' hex{4} | '\U' hex{5}
hex_escape = '\x' hex{2}
```

2020-12-15 16:25 UTC, dekrain commented on grammar.ebnf
> +bin_escape = '\b' ( '0' | '1' )+
[DISCUSSION] should this really be a thing?

2020-12-15 16:25 UTC, dekrain commented on grammar.ebnf
> +if = 'if' expr block [ 'else' block ]
maybe add support for non-awkward chaining of ~~yandere-dev style code~~ `if else`

2020-12-15 16:25 UTC, dekrain commented on grammar.ebnf
> +statement = ( for | while ) | ( ( declaration | expr | assignment ) ';' )
[DISCUSSION] this implies that `if` block must end with semicolons, I'd suggest more discussion about this

2020-12-15 16:29 UTC, noxabellus requested changes

2020-12-15 16:29 UTC, noxabellus commented on grammar.ebnf
> +escapes = '\n' | '\t' | '\r' | '\v' | '\f' | '\b' | '\'' | '\"' | '\\' | unicode_escape | hex_escape | bin_escape
Looks like the escaped single quote isnt recognized as being escaped...Maybe use "'" instead of '\''

2020-12-15 16:29 UTC, noxabellus commented on grammar.ebnf
> +string_literal = '"' ( escapes | utf8 )* '"'
Shouldnt string literals have the same optional prefixing `[ "utf8" | "utf16" | "utf32" ]` as the char literals?

2020-12-15 16:29 UTC, noxabellus commented on grammar.ebnf
> +literal = number_literal | string_literal | unicode_literal | char_literal
What is `unicode_literal`?

2020-12-15 16:29 UTC, noxabellus commented on grammar.ebnf
> +declaration = identifier ( ',' identifier )* ':' [ type ] [ '=' expr ]
This makes `my_var:;` a valid declaration

2020-12-15 16:29 UTC, noxabellus commented on grammar.ebnf
> +assignment = identifier '=' ( identifier | literal )
This doesnt allow assigning to dereferenced pointers, subscripts etc; and it doesnt allow assigning arbitrary expressions, such as the result of a function call. Think this should be `expr '=' expr`. This isnt precisely accurate as not all expressions are valid on the left side, but theres such a large amount as to be impractical to address (consider `@fn_call()[sub] = ...` for example ... Validating the left side is more of a semantic problem than a grammatical one

2020-12-15 16:29 UTC, noxabellus commented on grammar.ebnf
> +enum = 'enum' '{' enum_entry ( ',' enum_entry )* [ ',' ] '}'
Missing name for enum

2020-12-15 16:29 UTC, noxabellus commented on grammar.ebnf
> +type_compare = identifier 'is' ( [ '.' ] type )
This should be `variant_compare` and the thing after the `.` isn't a type, its just an identifier

2020-12-15 16:29 UTC, noxabellus commented on grammar.ebnf
> +cast = identifier 'as' ( [ '.' ] type )
Don't need the `.` here in the case of a type cast, only for variant casts. Should be something like `(('.' identifier) | type)`

2020-12-15 16:29 UTC, noxabellus commented on grammar.ebnf
> +call = identifier '(' expr ( ',' expr )* ')' ';'
Need to allow calling other kinds of expressions, not sure what this should look like. Probably just expr instead of identifier?

2020-12-15 16:29 UTC, noxabellus commented on grammar.ebnf
> +match_case = ( ( '.' identifier [ '@' identifier ] ) | ( identifier | literal ) | '*' ) block
Expression match arms should allow any arbitrary constant expression. Whether its constant or not is a semantic problem. So this should just be `... | expr | '*' )`

2020-12-15 16:29 UTC, noxabellus commented on grammar.ebnf
> +statement = ( for | while ) | ( ( declaration | expr | assignment ) ';' )
Shouldnt these just be under their respective categories?

2020-12-15 16:29 UTC, noxabellus commented on grammar.ebnf
> +block = '{' statement* [ expr ] '}'
Block is a valid expression and statement

2020-12-15 16:29 UTC, noxabellus commented on grammar.ebnf
> +statement = ( for | while ) | ( ( declaration | expr | assignment ) ';' )
Type declarations are listed under the statement category but aren't included here. I don't think they should be included here but they should be under their own "Item" category

2020-12-15 16:29 UTC, noxabellus commented on grammar.ebnf
> +program = ( function | sum | enum | multiline_comment )*
Missing structures and type aliases, global variable declarations, single line comments (presumably comments are allowed everywhere, too)

2020-12-15 16:29 UTC, noxabellus commented on examples/ack.mlk
> +}
Unnecessary parens in the predicate expressions and invalid use of trailing expressions... Need some `else`s

2020-12-15 17:02 UTC, Jackojc commented on grammar.ebnf
> +for = 'for' identifier [':' type] '=' expr ',' expr [',' expr] block
Good catch

2020-12-15 17:03 UTC, Jackojc commented on grammar.ebnf
> +hex_escape = '\x' hex+
Yeah I wasn't sure what notation to use for it but I guess that works.

2020-12-15 17:08 UTC, noxabellus commented on grammar.ebnf
> +if = 'if' expr block [ 'else' block ]
We need special support for variant matching here
```ebnf
predicate = expr [ 'is' '.' identifier '@' identifier ]
if = 'if' predicate block ( 'else' 'if' predicate block )*  [ 'else' block ]
```

2020-12-15 17:11 UTC, noxabellus commented on grammar.ebnf
> +match_case = ( ( '.' identifier [ '@' identifier ] ) | ( identifier | literal ) | '*' ) block
We probably should support multiple, comma separated case predicates per block
```ebnf
match = 'match' expr '{' match_case* '}'
match_predicate = ( ( '.' identifier [ '@' identifier ] ) | expr | '*' )
match_case =  match_predicate ( ',' match_predicate )* block
```

2020-12-15 17:12 UTC, Jackojc commented on grammar.ebnf
> +if = 'if' expr block [ 'else' block ]
Can you elaborate? I think `match` can handle this.

2020-12-15 17:13 UTC, Jackojc commented on grammar.ebnf
> +string_literal = '"' ( escapes | utf8 )* '"'
Yeah, whoops

2020-12-15 17:14 UTC, Jackojc commented on grammar.ebnf
> +literal = number_literal | string_literal | unicode_literal | char_literal
Oh whoops, remnant from an older iteration

2020-12-15 17:15 UTC, noxabellus commented on grammar.ebnf
> +expr = match | if | call | cast | type_compare | math
Missing:
`block`
binary ops, unary ops / `math`

2020-12-15 17:17 UTC, noxabellus commented on grammar.ebnf
> +pointer_type = '^'+ type
```ebnf
pointer_type = '^' type
```
Would suffice to convey this grammar, since `pointer_type` is part of `type` ... This doesnt cover the opaque pointer syntax proposed in the discord though. I believe that was just an unadorned `^` with no type following it. So maybe the grammar we want here is
```ebnf
pointer_type = '^' [ type ]
```

2020-12-15 17:18 UTC, dekrain commented on grammar.ebnf
> +if = 'if' expr block [ 'else' block ]
I mean something like
```
if ... {
} else if ... {
} else {
}
```
in the first example

2020-12-15 17:21 UTC, noxabellus commented on grammar.ebnf
> +statement = ( for | while ) | ( ( declaration | expr | assignment ) ';' )
Missing:
return
break, continue
goto

2020-12-15 17:22 UTC, noxabellus commented on grammar.ebnf
> +if = 'if' expr block [ 'else' block ]
> Can you elaborate? I think `match` can handle this.

Match only allows constant expressions

2020-12-15 17:23 UTC, dekrain commented on grammar.ebnf
> +assignment = identifier '=' ( identifier | literal )
so
```ebnf
assignment = (identifier | '@' expr) '=' ( identifier | literal )
```

2020-12-15 17:25 UTC, Jackojc commented on grammar.ebnf
> +enum = 'enum' '{' enum_entry ( ',' enum_entry )* [ ',' ] '}'
What do you mean?

2020-12-15 17:25 UTC, Jackojc commented on grammar.ebnf
> +type_compare = identifier 'is' ( [ '.' ] type )
`type` can be an identifier also, we may want to check something like `foo is i8` etc. Will change the name though.

2020-12-15 17:30 UTC, Jackojc commented on grammar.ebnf
> +call = identifier '(' expr ( ',' expr )* ')' ';'
Oh I suppose this would be useful if we add higher-order functions and want to support things like `foo()()`

2020-12-15 17:33 UTC, noxabellus commented on grammar.ebnf
> +statement = ( for | while ) | ( ( declaration | expr | assignment ) ';' )
Yeah I don't think that was the intention. I certainly don't want that. Being explicit about this would require separate grammars for if_expr and if_stmt? Possibly indicates we need block_expr and block_stmt as well, but as I touched on in my comment under the block grammar, its kind of down to semantic differences only that determine if a block is a valid expr

2020-12-15 17:35 UTC, noxabellus commented on grammar.ebnf
> +call = identifier '(' expr ( ',' expr )* ')' ';'
Yeah also arrays of functions, etc

2020-12-15 17:47 UTC, noxabellus commented on grammar.ebnf
> +assignment = identifier '=' ( identifier | literal )
Nah, that doesnt cover subscript, field access, etc. Like I said, theres too many possibilities to properly address in the grammar. Its a semantic problem.

2020-12-15 18:00 UTC, Jackojc commented on grammar.ebnf
> +assignment = identifier '=' ( identifier | literal )
I don't think that solves array subscripts dekrain, maybe it is just better to use `expr '=' expr` and check if its correct later on

2020-12-15 18:00 UTC, noxabellus commented on grammar.ebnf
> +type_compare = identifier 'is' ( [ '.' ] type )
> `type` can be an identifier also, we may want to check something like `foo is i8` etc. Will change the name though.
Fully disagree with this. In the current version plan (without generics) `foo is i8` is entirely pointless, and even if we wanted that later, it still would need to be separate cases `('.' identifier) | type`

2020-12-15 18:02 UTC, noxabellus commented on grammar.ebnf
> +enum = 'enum' '{' enum_entry ( ',' enum_entry )* [ ',' ] '}'
I would assume enum variants would be scoped rather than poluting the namespace like C. In other words enums would be defined like ```
enum MyEnum { A, B, C }
```
and referenced like `MyEnum.A`

2020-12-15 18:04 UTC, noxabellus commented on grammar.ebnf
> +enum = 'enum' '{' enum_entry ( ',' enum_entry )* [ ',' ] '}'
I think we should allow defining the backing type for enums and sum discriminators.
e.g. ```
enum MyEnum: u8 { A, B, C }``
would ensure that MyEnum is exactly 1 byte in size

2020-12-15 18:06 UTC, dekrain commented on grammar.ebnf
> +enum = 'enum' '{' enum_entry ( ',' enum_entry )* [ ',' ] '}'
wouldn't we do
```
type MyEnum : enum { A, B, C }
```

2020-12-15 18:07 UTC, Jackojc commented on grammar.ebnf
> +enum = 'enum' '{' enum_entry ( ',' enum_entry )* [ ',' ] '}'
I think we could probably just use the type that is small enough to still cover all of the entries. I don't see anyone really wanting different semantics than that.

2020-12-15 18:07 UTC, noxabellus commented on grammar.ebnf
> +enum = 'enum' '{' enum_entry ( ',' enum_entry )* [ ',' ] '}'
I think what we discussed for `type` aliases was that the right hand side of the `:` is a type expression, and enum isnt a valid type expression

2020-12-15 18:09 UTC, noxabellus commented on grammar.ebnf
> +enum = 'enum' '{' enum_entry ( ',' enum_entry )* [ ',' ] '}'
Fully disagree, this was what they thought when they defined the C grammar, and then every compiler had to add hacky attributes to allow this because people prefer to be explicit.

2020-12-15 18:11 UTC, Jackojc commented on grammar.ebnf
> +enum = 'enum' '{' enum_entry ( ',' enum_entry )* [ ',' ] '}'
I think it's best to keep it as to ensure that the enum is properly namespaced, if we make it a type expression, you would have an enum which pollutes global scope.

2020-12-15 18:12 UTC, noxabellus commented on grammar.ebnf
> +enum = 'enum' '{' enum_entry ( ',' enum_entry )* [ ',' ] '}'
I do think it should be optional though
```ebnf
enum = 'enum' identifier [':' type] '{' enum_entry ( ',' enum_entry )* [ ',' ] '}'
```

2020-12-15 18:12 UTC, Jackojc commented on grammar.ebnf
> +enum = 'enum' '{' enum_entry ( ',' enum_entry )* [ ',' ] '}'
Do you think it really makes sense for sum types though?

2020-12-15 18:13 UTC, noxabellus commented on grammar.ebnf
> +enum = 'enum' '{' enum_entry ( ',' enum_entry )* [ ',' ] '}'
Absolutely. If we didn't have that we couldn't reliably cross FFI boundaries with sum types

2020-12-15 18:18 UTC, Anonymus-Player commented on grammar.ebnf
> +integer_literal = ( digit | '_' )+
How are we gonna handle inline casting eg:
Rust has something along the line of:
`let value = 42u64;`
While C++ has something like:
`auto value = 42ul`

2020-12-15 18:21 UTC, dekrain commented on grammar.ebnf
> +integer_literal = ( digit | '_' )+
`value := 42;`

2020-12-15 18:23 UTC, noxabellus commented on grammar.ebnf
> +integer_literal = ( digit | '_' )+
Think he was referring to the `u64` / `ul` bit

2020-12-15 18:23 UTC, Jackojc commented on grammar.ebnf
> +enum = 'enum' '{' enum_entry ( ',' enum_entry )* [ ',' ] '}'
Fair

2020-12-15 18:24 UTC, Anonymus-Player commented on grammar.ebnf
> +integer_literal = ( digit | '_' )+
Ok, but what if i want it to be an explicit 16 bit integer for example, do we have literals for that, or do i need to explicitly cast it/

2020-12-15 18:25 UTC, Jackojc commented on grammar.ebnf
> +integer_literal = ( digit | '_' )+
I'm not sure what the best way to handle this is honestly. We could go the route of just requiring you to specify the type if its deduced incorrectly from what you want.

2020-12-15 18:27 UTC, noxabellus commented on grammar.ebnf
> +integer_literal = ( digit | '_' )+
Yeah, `value: u64 = 42` Would be how you did it under the current grammar.
Literals coerce to whichever type is inferred, so most of the time you wouldn't need to state it, outside of declarations

2020-12-17 18:44 UTC, Jackojc commented on grammar.ebnf
> +program = ( function | sum | enum | multiline_comment )*
Yes to everything except module stuff for now. I think single line comments are just going to be handled lexically whereby it just advances until it hits a newline then returns the next valid token. Multiline comments are just a special case to allow nesting.

2020-12-17 19:14 UTC, Jackojc commented on grammar.ebnf
> +block = '{' statement* [ expr ] '}'
I _think_ I've addressed it by explicitly requiring semicolons on things like declarations and assignments and not requiring statements to end in semicolon anymore but I'll let you read it later and see.

2020-12-17 19:15 UTC, Jackojc commented on grammar.ebnf
> +statement = ( for | while ) | ( ( declaration | expr | assignment ) ';' )
For now I've just added them to the statement construct but maybe we can rework and clean up the grammar in the next revision.

2020-12-17 19:18 UTC, Jackojc commented on grammar.ebnf
> +statement = ( for | while ) | ( ( declaration | expr | assignment ) ';' )
I think I've addressed this but will need to be checked in the new revision.

2020-12-17 19:47 UTC, Jackojc commented
Addressed requested changes in latest commit, please review.

2020-12-18 01:01 UTC, noxabellus requested changes
Looks like things are progressing well just got a few more details to work out

2020-12-18 01:01 UTC, noxabellus commented on grammar.ebnf
> +array_type = '[' ( integer_literal | identifier ) ( ',' ( integer_literal | identifier ) )* ']' type
Missed this before but I think it should be arbitrary exprs for array dimensions
```ebnf
array_type = '[' expr ( ',' expr )* ']' type
```
Any constant expression should be valid here, and the constness is a semantic distinction

2020-12-18 01:01 UTC, noxabellus commented on grammar.ebnf
> +tuple_type = '(' ( identifier | literal )* ')'
Think this is copy pasta from `array_type`? Should be
```ebnf
tuple_type = '(' type ( ',' type )* ')'
```
Where a single element tuple just evaluates to the interior type semantically

2020-12-18 01:01 UTC, noxabellus commented on grammar.ebnf
> +type = array_type | pointer_type | fn_type | struct_type | identifier
Missing `tuple_type`

2020-12-18 01:01 UTC, noxabellus commented on grammar.ebnf
> +type = array_type | pointer_type | fn_type | struct_type | identifier
Personally, I don't think `struct_type` should be here. I don't think anonymous struct types are a desirable feature. This should be with `sum` and `enum`

2020-12-18 01:01 UTC, noxabellus commented on grammar.ebnf
> +predicate = expr [ 'is' '.' identifier '@' identifier ]
I proposed this grammar in the last review but I realize now it's not quite right. This won't allow multiple `is` bindings, nor will it allow `is` binding to be followed by additional logical operators. Consider these examples:
```
if x is .A @ bind0 and y is .B @ bind1 { .. }
```
```
if x is .A @ bind0 and y == z { .. }
```
```
if x == y and z is .A @ bind0 { .. }
```
I think to resolve this we need to allow `@` bindings in all `is` expressions and leave the validity/usability of the binding as a semantic distinction

2020-12-18 01:01 UTC, noxabellus commented on grammar.ebnf
> +array_subscript = identifier '[' array_index ( ',' array_index )* ']'
Subscript should allow any expr

2020-12-18 01:01 UTC, noxabellus commented on grammar.ebnf
> +unary_op = '@' expr
This way of declaring rules is pretty nasty in my opinion

2020-12-18 01:01 UTC, noxabellus commented on grammar.ebnf
> +match_case =  match_predicate ( ',' match_predicate )* block
I don't think we want to have multiple @ bindings when using comma separated predicates. The names would all have to be the same to make semantic sense, anyway. I'd prefer to be able to do:
```
match x {
  .A, .B @ bind0 { .. }
  ..
}
```
Not sure how to best state this in grammar from

2020-12-18 01:01 UTC, noxabellus commented on grammar.ebnf
> +bin_op = expr '^' expr
Missing logical and bitwise ops

2020-12-18 01:01 UTC, noxabellus commented on grammar.ebnf
> +call = expr '(' expr ( ',' expr )* ')'
This indicates function calls must have at least one argument

2020-12-18 01:01 UTC, noxabellus commented on grammar.ebnf
> +# Misc
I think we should rename this section to `# Program` and move the declarations and such here

2020-12-18 01:27 UTC, noxabellus commented on grammar.ebnf
> +statement = ( for | while | alias ) | ( declaration | assignment | expr )
This still indicates a `;` is required after `if` and `match`

2020-12-18 01:30 UTC, noxabellus commented on grammar.ebnf
> +loop_body = '{' ( statement | 'break' | 'continue' )* '}'
This is weird. I get that you don't want to allow these control flow keywords in the wrong places but this does weird things like not allow you to return from inside a loop. I would say make `return`, `break`, and `continue` just regular statements, and use regular instead of these `_body` rules. Yes this leads to some weird cases but they're semantic ones and can't be controlled with grammar in a sensible way

2020-12-18 01:32 UTC, noxabellus commented on grammar.ebnf
> +expr = match | if | call | cast | type_compare | math | block | field_access | array_subscript | literal | operator
Missing semantic group expression
```ebnf
sem_group = '(' expr ')'
```

2020-12-18 01:41 UTC, Jackojc commented on grammar.ebnf
> +array_type = '[' ( integer_literal | identifier ) ( ',' ( integer_literal | identifier ) )* ']' type
I actually updated it to include identifiers which might have made it stand out more haha but I think using expr is probably fair.

2020-12-18 01:45 UTC, Jackojc commented on grammar.ebnf
> +type = array_type | pointer_type | fn_type | struct_type | identifier
Yeah good point I completely missed that.

2020-12-18 01:47 UTC, Jackojc commented on grammar.ebnf
> +unary_op = '@' expr
Would you prefer a chain of alternatives using `|`?

2020-12-18 01:49 UTC, noxabellus commented on grammar.ebnf
> +unary_op = '@' expr
What about
```ebnf
bin_op = expr ( '+' | '-' | '*' | '/' | '^' ) expr
```

2020-12-18 01:50 UTC, noxabellus commented on grammar.ebnf
> +unary_op = '@' expr
Though, when we get the full list of ops that might get a bit unwieldy

2020-12-18 01:50 UTC, noxabellus commented on grammar.ebnf
> +bin_op = expr '^' expr
Also missing comparisons

2020-12-18 01:55 UTC, Jackojc commented on grammar.ebnf
> +unary_op = '@' expr
It's definitely not pretty lol

2020-12-18 02:03 UTC, noxabellus commented on grammar.ebnf
> +unary_op = '@' expr
Another option:
```ebnf
infix = '+' | '-' | '*' | '/' | '^'
      | '==' | '!=' | '<=' | '>=' | '<' | '>'
      | 'and' | 'or'
      | '&' | '|' | '^' | '<<' | '>>'
binop = expr infix expr
```

2020-12-18 02:06 UTC, noxabellus commented on grammar.ebnf
> +expr = match | if | call | cast | type_compare | math | block | field_access | array_subscript | literal | operator
Nevermind, this is covered under `operator`

2020-12-18 02:14 UTC, noxabellus commented on grammar.ebnf
> +statement = ( for | while | alias ) | ( declaration | assignment | expr )
Actually no this indicates no `;` is required after any expr

2020-12-18 04:18 UTC, Jackojc commented
Changes pushed

2020-12-18 04:30 UTC, noxabellus requested changes
Nearly there now

2020-12-18 04:30 UTC, noxabellus commented on grammar.ebnf
> +function = 'fn' identifier '(' declaration ( ',' declaration )* ')' [ type ] block
`declaration` won't work here

2020-12-18 04:30 UTC, noxabellus commented on grammar.ebnf
> +struct = 'struct' identifier '{' ( declaration ';' )* '}'
`declaration` won't work here

2020-12-18 04:30 UTC, noxabellus commented on grammar.ebnf
> +enum_entry = identifier [ '=' literal ]
Should be
```ebnf
enum_entry = identifier [ '=' expr ]
```
Any constant expression is valid here

2020-12-18 05:14 UTC, noxabellus approved these changes, later dismissed
Think this is good to go for the first version's grammar

2020-12-18 18:11 UTC, serbuvlad commented on examples/ack.mlk
> +# Ackermann function (http://rosettacode.org/wiki/Ackermann_function)
http links should be https?

2020-12-18 18:27 UTC, serbuvlad commented on grammar.ebnf
> +for = 'for' identifier ':' [type] '=' expr ',' expr [',' expr] block
This is problematic for 2 reasons: The big one is that all example programs that use for would be wrong, because assignments aren't expressions, and do not fit in the third field. On a more minor point, why should we limit the first part of the for to a single variable.

I think the traditional `for non-block-statement; expression; non-block-statement {` is better and cleaner. Would require some grammar reworking in other places.

2020-12-18 18:28 UTC, serbuvlad commented on grammar.ebnf
> +if = 'if' expr block 'else' ( block | if )
The else should be optional

2020-12-18 19:10 UTC, Jackojc commented on examples/ack.mlk
> +# Ackermann function (http://rosettacode.org/wiki/Ackermann_function)
Unfortunately, rosettacode doesn't seem to use TLS.

2020-12-19 00:11 UTC, noxabellus approved these changes

2020-12-19 01:10 UTC, merged